version: '3.7'
services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    expose:
      - '3306'
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT}
       MYSQL_DATABASE: 'scholarscrape'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'pass'

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/my-app:/code
    ports:
      - 3000:3000

  scraper:
    build: ./scraper
    volumes:
      -  ./scraper:/code


volumes:
  db-data:
